package config

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestReadConfigFileMissing verifies the documented contract: a missing
// config.toml returns a zero-value FileConfig and no error. This is the
// state of a fresh install before the operator ever runs `dclaw config set`.
func TestReadConfigFileMissing(t *testing.T) {
	dir := t.TempDir()
	cfg, err := ReadConfigFile(dir)
	if err != nil {
		t.Fatalf("ReadConfigFile on missing: got error %v", err)
	}
	if cfg.WorkspaceRoot != "" {
		t.Fatalf("expected zero FileConfig, got %+v", cfg)
	}
}

// TestReadConfigFileRoundTrip writes a config, reads it back, asserts
// equality, then overwrites and reads again to verify Write-replaces-write
// semantics.
func TestReadConfigFileRoundTrip(t *testing.T) {
	dir := t.TempDir()
	wanted := FileConfig{WorkspaceRoot: "/Users/alice/dclaw-agents"}
	if err := WriteConfigFile(dir, wanted); err != nil {
		t.Fatalf("WriteConfigFile: %v", err)
	}
	got, err := ReadConfigFile(dir)
	if err != nil {
		t.Fatalf("ReadConfigFile: %v", err)
	}
	if got != wanted {
		t.Fatalf("round trip mismatch: got %+v want %+v", got, wanted)
	}

	// Overwrite and round-trip again.
	wanted2 := FileConfig{WorkspaceRoot: "/tmp/other"}
	if err := WriteConfigFile(dir, wanted2); err != nil {
		t.Fatalf("WriteConfigFile #2: %v", err)
	}
	got2, err := ReadConfigFile(dir)
	if err != nil {
		t.Fatalf("ReadConfigFile #2: %v", err)
	}
	if got2 != wanted2 {
		t.Fatalf("second round trip mismatch: got %+v want %+v", got2, wanted2)
	}
}

// TestReadConfigFileInvalidTOML asserts the parser rejects unrecognized
// shapes instead of silently ignoring them. This is the safety property
// the homegrown parser owes callers.
func TestReadConfigFileInvalidTOML(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config.toml")
	bad := `workspace-root /oops-no-equals
`
	if err := os.WriteFile(path, []byte(bad), 0o600); err != nil {
		t.Fatalf("seed bad config: %v", err)
	}
	_, err := ReadConfigFile(dir)
	if err == nil {
		t.Fatalf("expected parse error on malformed config.toml")
	}
	if !strings.Contains(err.Error(), "unrecognized shape") {
		t.Fatalf("expected 'unrecognized shape' in error, got %v", err)
	}
}

// TestReadConfigFileWithComments verifies comments and blank lines are
// skipped gracefully without triggering the reject-unknown-shape path.
func TestReadConfigFileWithComments(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config.toml")
	content := `# dclaw config file
# generated by 'dclaw config set workspace-root'

workspace-root = "/Users/alice/ws"
# trailing comment
`
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatalf("write: %v", err)
	}
	cfg, err := ReadConfigFile(dir)
	if err != nil {
		t.Fatalf("read with comments: %v", err)
	}
	if cfg.WorkspaceRoot != "/Users/alice/ws" {
		t.Fatalf("got %+v", cfg)
	}
}

// TestWriteConfigFileRejectsQuote verifies the grammar guard: a value
// containing a double-quote cannot be round-tripped and must be rejected
// at write time.
func TestWriteConfigFileRejectsQuote(t *testing.T) {
	dir := t.TempDir()
	err := WriteConfigFile(dir, FileConfig{WorkspaceRoot: `/oops"embedded`})
	if err == nil {
		t.Fatalf("expected error on embedded double-quote")
	}
}

// TestWriteConfigFileMode0600 verifies the file is created with mode 0600.
func TestWriteConfigFileMode0600(t *testing.T) {
	dir := t.TempDir()
	if err := WriteConfigFile(dir, FileConfig{WorkspaceRoot: "/tmp"}); err != nil {
		t.Fatalf("WriteConfigFile: %v", err)
	}
	st, err := os.Stat(filepath.Join(dir, "config.toml"))
	if err != nil {
		t.Fatalf("stat: %v", err)
	}
	if st.Mode().Perm() != 0o600 {
		t.Fatalf("expected mode 0600, got %v", st.Mode().Perm())
	}
}
